import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const applicants = [
  {
    fullName: "Marina Alvez",
    email: "marina.alvez@example.com",
    pronouns: "she/her",
    phone: "555-0101",
    school: "Coastal State University",
    educationLevel: "undergraduate",
    gradYear: "2027",
    fieldOfStudy: "Computer Science",
    hackathonsAttended: "3-5",
    technicalSkills: "TypeScript, React, Python, computer vision",
    portfolioUrl: "https://github.com/marinaalvez",
    dietaryRestrictions: "Vegetarian",
    essayWhy:
      "I want to build something with a team under real time pressure and learn from people further along than me.",
    essayLearn: "How to design systems that scale past a weekend hack.",
    essayProject:
      "Built a reef-health tracker using satellite imagery and a lightweight CNN, deployed to a Raspberry Pi buoy.",
    currentZone: "hadal",
    submitted: true,
    status: "ACCEPTED",
    scoreTechnical: 9,
    scoreCreativity: 8.5,
    scoreFit: 9,
    reviewerNotes: "Strong technical background, clear communicator. Easy yes.",
  },
  {
    fullName: "Devon Cho",
    email: "devon.cho@example.com",
    pronouns: "he/him",
    phone: "555-0102",
    school: "Riverbend Institute of Technology",
    educationLevel: "bootcamp",
    gradYear: "2026",
    fieldOfStudy: "Full-stack web development",
    hackathonsAttended: "1-2",
    technicalSkills: "JavaScript, Node, Postgres",
    portfolioUrl: "https://devoncho.dev",
    dietaryRestrictions: "None",
    essayWhy: "Career changer looking to break into tech, hackathons feel like the fastest way to learn in public.",
    essayLearn: "How experienced engineers approach ambiguous problems.",
    essayProject: "A budgeting app for freelancers that reconciles multiple invoice platforms automatically.",
    currentZone: "hadal",
    submitted: true,
    status: "PENDING",
  },
  {
    fullName: "Priya Natarajan",
    email: "priya.n@example.com",
    pronouns: "she/her",
    phone: "555-0103",
    school: "Northgate University",
    educationLevel: "graduate",
    gradYear: "2026",
    fieldOfStudy: "Human-Computer Interaction",
    hackathonsAttended: "6+",
    technicalSkills: "Figma, React, accessibility auditing, Swift",
    portfolioUrl: "https://priyan.design",
    dietaryRestrictions: "Gluten-free",
    essayWhy: "Hackathons are where my best design work happens — constraints force clarity.",
    essayLearn: "Hardware prototyping, I've only ever shipped software.",
    essayProject:
      "Redesigned a hospital intake kiosk flow that cut average wait-time confusion complaints by half in user testing.",
    currentZone: "hadal",
    submitted: true,
    status: "WAITLISTED",
    scoreTechnical: 6.5,
    scoreCreativity: 9.5,
    scoreFit: 7.5,
    reviewerNotes: "Design-heavy profile, less clear on technical execution under time pressure. Waitlist for now.",
  },
  {
    fullName: "Sam Okafor",
    email: "sam.okafor@example.com",
    pronouns: "they/them",
    phone: "555-0104",
    school: "Lakeshore Community College",
    educationLevel: "undergraduate",
    gradYear: "2028",
    fieldOfStudy: "Data Science",
    hackathonsAttended: "0",
    technicalSkills: "Python, pandas, scikit-learn",
    portfolioUrl: "",
    dietaryRestrictions: "None",
    essayWhy: "This would be my first hackathon and I want to see if I can hang with people who've done this before.",
    essayLearn: "How to work on a team instead of solo class projects.",
    essayProject: "A small model predicting bus arrival delays from historical transit data for my city.",
    currentZone: "hadal",
    submitted: true,
    status: "REJECTED",
    scoreTechnical: 4,
    scoreCreativity: 5,
    scoreFit: 4.5,
    reviewerNotes: "Promising but essays suggest not quite ready for this event's pace. Encourage to reapply next cycle.",
  },
  {
    fullName: "Elif Yildiz",
    email: "elif.yildiz@example.com",
    pronouns: "she/her",
    phone: "555-0105",
    school: "Bluewater Technical College",
    educationLevel: "undergraduate",
    gradYear: "2027",
    fieldOfStudy: "Software Engineering",
    hackathonsAttended: "1-2",
    technicalSkills: "Go, Docker, Kubernetes",
    portfolioUrl: "https://github.com/eyildiz",
    dietaryRestrictions: "",
    essayWhy: "",
    essayLearn: "",
    essayProject: "",
    currentZone: "abyssal",
    submitted: false,
    status: "PENDING",
  },
  {
    fullName: "Marcus Webb",
    email: "marcus.webb@example.com",
    pronouns: "",
    phone: "555-0106",
    school: "Northgate University",
    educationLevel: "undergraduate",
    gradYear: "2029",
    fieldOfStudy: "",
    hackathonsAttended: "",
    technicalSkills: "",
    portfolioUrl: "",
    dietaryRestrictions: "",
    essayWhy: "",
    essayLearn: "",
    essayProject: "",
    currentZone: "midnight",
    submitted: false,
    status: "PENDING",
  },
  {
    fullName: "Yuki Tanaka",
    email: null,
    pronouns: "",
    phone: "",
    school: "",
    educationLevel: "",
    gradYear: "",
    fieldOfStudy: "",
    hackathonsAttended: "",
    technicalSkills: "",
    portfolioUrl: "",
    dietaryRestrictions: "",
    essayWhy: "",
    essayLearn: "",
    essayProject: "",
    currentZone: "twilight",
    submitted: false,
    status: "PENDING",
  },
];

async function main() {
  for (const a of applicants) {
    await prisma.applicant.create({ data: a });
  }
  console.log(`Seeded ${applicants.length} applicants.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
